### ISSUE TITLE
Smoke test for WPML Compatibility

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#23] opened 2023-09-20 05:19 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes with new enhancements/features, we may have problems with WPML so automating smoke tests will be added value

**Describe the solution you'd like**
We need to confirm the following with different WPML setups (  directory, query string, domain base)
1- UI is correct for cached and no cache version of main and sub-language
2- No broken links on the page
3- No console error nor error in debug.log
4- Switch language from FE/BE is not causing any error
5- optimization is working correctly on main and sub-language

**Describe alternatives you've considered**

**Additional context**
- theses tests shall run with every new feature or feature revamp
- recommend run those tests with different optimization options enabled
- Sample test https://wpmediaqa.testrail.io/index.php?/cases/view/14655&group_by=cases:section_id&group_id=4327&group_order=asc&display_deleted_cases=0 => we can have something like `Should 'feature-name' works on WPML` feature-name can be Minify CSS, RUCSS, Minify JS, Combine JS, Defer JS, Delay JS, LL image, LL BG I, LL video, CDN (template here for LL BGI, however, we can use suitable template/feature)

**Comment by jeawhanlee** [comment] 2023-11-13 16:33
### Scope a solution ✅
First we need to have WPML Installed but not activated(We will activate it every time we run tests related to it)
For this we will need to make use of a conditional hook (`Before` and `After` with a `@wpml` tag) to activate it before each scenario and deactivate it after each scenario.

Since it looks like we will be running the same kind of tests with different WPR options enabled. I'll suggest we make this a param that can be parsed via the CLI, something like `npm run test:wpml --wprOption="rucss"` then we can grab the value of `wprOption` and enable it.

We will also update our `SCENARIO_URLS` option in our config with new template labels for various WPR options to perform VR testing. Then we will load the required template based on the WPR option that is parsed in the CLi

We will need to create new step definitions for the following steps:
- checking for broken links on page
- Switch lang from FE/BE
Rest of the steps are already defined like checking Visual Regression and console errors.

### Estimate the effort ✅
[S]

**Comment by jeawhanlee** [comment] 2023-11-16 11:14
### E2E Steps

Scenario: WPML with Directory option enabled
- Given All WPR settings is enabled
- When I scroll to the bottom
- And I Switch languages on the frontend
- And I scroll to the bottom
- Then there is no visual regression
- Then there is no console error different from uncached version with ?nowprocket
- Then no error in debug.log

Scenario: WPML with query string option enabled
- Given All WPR settings is enabled
- When I scroll to the bottom
- And I Switch languages on the frontend
- And I scroll to the bottom
- Then there is no visual regression
- Then there is no console error different from uncached version with ?nowprocket
- Then no error in debug.log
 
@wp-media/qa-team Kindly confirm that these are the expected steps.

Awaiting env setup from @wp-media/qa-team

**Comment by MathieuLamiot** [comment] 2024-02-05 14:38
should be wrapped up today

**Comment by hanna-meda** [comment] 2024-03-28 15:30
@Khadreal,
Having a run of the tests, I see multiple step definitions match in both scenarios:
<img width="819" alt="Screenshot 2024-03-28 at 17 32 43" src="https://github.com/wp-media/wp-rocket-e2e/assets/93833759/3894ecc4-a8c6-4e1b-8b04-b8d7f31d68e9">   
   if you can have a look. 
   
To be noted, there is a 3rd scenario, WPML with Domain option enabled, not covered by automation, because on the e2e env the domain setup does not work currently. 
@piotrbak you think it is worth investigating again why that setup is not working on e2e (so far is only working on rocketlabs), and make it work? cc @Mai-Saad

**Comment by Khadreal** [comment] 2024-04-03 12:01
@hanna-meda I have pushed a fix for the error, please try to run the test again.

**Closed as completed** 2024-04-03 16:56 UTC
Labels: effort: [S], priority: medium
